#pragma once

#define NEEDLE_RESOURCE_RENDERING_DEVICE_CONTEXT 0x43564452444E4552ui64

namespace hh::needle {
    struct SourceBufferSetting;
    struct IndexBuffer;
    class ShaderObject;
    class InstanceParameterContainerData;
    class RenderingDeviceContext : public TNeedleRefcountResource<NEEDLE_RESOURCE_RENDERING_DEVICE_CONTEXT, NeedleRefcountResource> {
    public:
        virtual void BeginRendering() = 0;
        virtual RenderingCommandList* EndRendering() = 0;
        virtual bool ExecuteRendering(RenderingCommandList* commandList) = 0;
        virtual bool UnkFunc1() = 0; // before render
        virtual bool UnkFunc2() = 0; // after render
        virtual uint32_t UnkFunc3() = 0;
        virtual uint64_t UnkFunc4() = 0;
        virtual uint64_t UnkFunc5() = 0;
        virtual uint64_t UnkFunc6b() = 0;
        virtual void SetVertexBuffer(unsigned int bufferSize, SourceBufferSetting* unused, unsigned int totalSize) = 0;
        virtual uint64_t UnkFunc8() = 0;
        virtual uint64_t UnkFunc9() = 0;
        virtual uint64_t UnkFunc10() = 0;
        virtual uint64_t UnkFunc11() = 0;
        virtual uint64_t UnkFunc12() = 0;
        virtual uint64_t UnkFunc13() = 0;
        virtual void DrawVerticesUP(const void* vertices, unsigned int vertexCount, unsigned int vertexStride) = 0;
        virtual void DrawIndexedVerticesUP(const unsigned short* indices, unsigned int indexCount, const void* vertices, unsigned int vertexCount, unsigned int vertexStride) = 0;
        virtual void DrawIndexed(unsigned int indexCount, unsigned int startIndexLocation, int baseVertexLocation) = 0;
        virtual void DrawIndexedInstanced(unsigned int indexCountPerInstance, unsigned int instanceCount, unsigned int startIndexLocation, int baseVertexLocation, unsigned int startInstanceLocation) = 0;
        virtual void DrawIndexedInstancedIndirect(NeedleRefcountResource* bufferForArgs, unsigned int alignedByteOffsetForArgs) = 0;
        virtual void Draw(unsigned int vertexCount, unsigned int startVertexLocation) = 0;
        virtual void Dispatch(unsigned int threadGroupCountX, unsigned int threadGroupCountY, unsigned int threadGroupCountZ) = 0;
        virtual void DispatchIndirect(NeedleRefcountResource* bufferForArgs, unsigned int alignedByteOffsetForArgs) = 0;
        virtual void SetShaderObject(const ShaderObject* shaderObject, const InstanceParameterContainerData** ipcd, unsigned int unkParam1, const unsigned char* unkParam2, unsigned int unkParam3) = 0;
        virtual void SetPrimitiveTopology(PrimitiveTopology primitiveTopology) = 0;
        virtual void ResetShaderResource() = 0;
        virtual void SetShaderParameter(const void* statusContext) = 0;
        virtual void SetShaderParameterNativeChunk(const void* statusContext) = 0; // ShaderNativeStatusContext
        virtual void FlushStatus() = 0;
        virtual void FlushClear() = 0;
        virtual void FlushInternal() = 0;
        virtual void FlushInternalWithoutDirty() = 0;
        virtual void InvalidateStatus() = 0;
        virtual void SetVertexBuffer(unsigned int startSlot, const SourceBufferSetting* sourceBufferSetting, unsigned int numBuffers) = 0;
        virtual void SetIndexBuffer(const IndexBuffer* indexBuffer, unsigned int offset) = 0;
        virtual void DoNothing1() = 0;
        virtual void DoNothing2() = 0;
        virtual void SetPixelShader(PixelShader* shader) = 0;
        virtual void SetComputeShader(ComputeShader* shader) = 0;
        virtual void DoNothing3() = 0;
        virtual void SetVertexBufferDirect() = 0;
        virtual void SetIndexBufferDirect() = 0;
        virtual void SetConstantBufferDirect() = 0;
        virtual void SetRegularBufferDirect() = 0;
        virtual void SetShaderConstantMemory(ShaderStage shaderStage, unsigned int slot, const void* data, size_t size) = 0;
        virtual void SetShaderParameterFloat(CNameIDObject* parameterName, const float* data, unsigned int count) = 0;
        virtual void SetShaderParameterInt(CNameIDObject* parameterName, const float* data, unsigned int count) = 0;
        virtual void SetShaderParameterBool(CNameIDObject* parameterName, const float* data, unsigned int count) = 0;
        virtual void SetShaderResourceView(ShaderStage shaderStage, unsigned int slot, void* unkParam) = 0;
        virtual void SetTexture(CNameIDObject* parameterName, Texture* texture) = 0;
        virtual void SetSampler(ShaderStage shaderStage, unsigned int slot, const SamplerStateSetting* samplerStateSetting) = 0;
        virtual void UnkFunc49() = 0;
        virtual void SetTextureSampler(CNameIDObject* parameterName, Texture* texture, const SamplerStateSetting* samplerStateSetting) = 0;
        virtual void SetCullMode(CullMode cullMode) = 0;
        virtual void SetFillMode(FillMode fillMode) = 0;
        virtual void SetScissorEnable(bool enabled) = 0;
        virtual void UnkFunc54() = 0;
        virtual void SetDepthEnable(bool enabled) = 0;
        virtual void SetDepthWriteEnable(bool enabled) = 0;
        virtual void SetDepthComparisonFunc(ComparisonFunc comparisonFunc) = 0;
        virtual void SetTwoSidedStencil(bool unkParam1, ComparisonFunc comparisonFunc1, int unkParam21, unsigned int unkParam31, StencilOp stencilOp11, StencilOp stencilOp12, StencilOp stencilOp13, unsigned int unkParam41, ComparisonFunc comparisonFunc2, int unkParam22, unsigned int unkParam32, StencilOp stencilOp21, StencilOp stencilOp22, StencilOp stencilOp23, unsigned int unkParam42) = 0;
        virtual void SetStencil(bool unkParam1, ComparisonFunc comparisonFunc, int unkParam2, unsigned int unkParam3, StencilOp stencilOp1, StencilOp stencilOp2, StencilOp stencilOp3, unsigned int unkParam4) = 0;
        virtual void SetColorWriteEnable(bool enabled) = 0;
        virtual void UnkFunc61() = 0;
        virtual void SetBlendDescSetting() = 0;
        virtual void SetBlendModeWithAlpha(bool enabled, BlendMode src, BlendMode dst, BlendOp op, BlendMode alphaSrc, BlendMode alphaDst, BlendOp alphaOp) = 0;
        virtual void SetBlendMode(bool enabled, BlendMode src, BlendMode dst, BlendOp op) = 0;
        virtual void SetViewport(const ViewportSetting* viewportSetting, unsigned int count) = 0;
        virtual void UnkFunc66() = 0;
        virtual void SetScissor(const Rectangle* scissorRects, unsigned int count) = 0;
        virtual uint64_t UnkFunc68() = 0;
        virtual uint64_t UnkFunc69() = 0;
        virtual uint64_t UnkFunc70() = 0;
        virtual void GetRsFlagMask(RsFlagMask& rsFlagMask) = 0;
        virtual void SetRenderTargets(const RenderTargetsSetting& renderTargetsSetting) = 0;
        virtual void GetRenderTargets(RenderTargetsSetting& renderTargetsSetting) = 0;
        virtual void ClearRenderTarget(const RenderTarget* renderTarget, const float (&colorRGBA)[4]) = 0;
        virtual void ClearDepthStencil(const DepthStencil* depthStencil, unsigned int clearFlags, float depth, unsigned char stencil) = 0;
        virtual void SetUnorderedAccessViews(const UnorderedAccessViewsSetting& unorderedAccessViewsSetting) = 0;
        virtual uint64_t UnkFunc77() = 0;
        virtual void ClearUnorderedAccessViewFloat(const UnorderedAccessView* uav, const float (&values)[4]) = 0;
        virtual void ClearUnorderedAccessViewUint(const UnorderedAccessView* uav, const unsigned int (&values)[4]) = 0;
        virtual void Resolve(const NeedleRefcountResource* srcResource, unsigned int srcLevel, NeedleRefcountResource* dstResource, unsigned int dstLevel) = 0;
        virtual void ResolveMain(const NeedleRefcountResource* srcResource, NeedleRefcountResource* dstResource) = 0;
        virtual void CopySubresourceRegion(const NeedleRefcountResource* srcResource, NeedleRefcountResource* dstResource) = 0;
        virtual void CopyResource(const NeedleRefcountResource* srcResource, unsigned int srcLevel, NeedleRefcountResource* dstResource, unsigned int dstLevel) = 0;
        virtual bool DoNothing4() = 0;
        virtual bool Maybe_IsCapturingNow() = 0;
        virtual void PushMarker(const char* id) = 0;
        virtual void PopMarker() = 0;
        virtual void SetMarker(const char* id) = 0;
        virtual void GenerateMips(Texture* texture) = 0;
        virtual void Map(const NeedleRefcountResource* resource, unsigned int unkParam, MapType mapType, SRawImageInfo* rawImageInfo) = 0;
        virtual void Unmap(const NeedleRefcountResource* resource, const SRawImageInfo* rawImageInfo) = 0;
        virtual void UpdateResource(const NeedleRefcountResource* resource, unsigned int level, const Box& box, const SRawImageInfo rawImageInfo) = 0;
        virtual uint64_t UnkFunc93() = 0;
        virtual uint64_t UnkFunc94() = 0;
        virtual uint64_t UnkFunc95() = 0;
        virtual uint64_t UnkFunc96() = 0;
        virtual uint64_t UnkFunc97() = 0;
        virtual uint64_t UnkFunc98() = 0;
        virtual uint64_t UnkFunc99() = 0;
        virtual uint64_t UnkFunc100() = 0;
        virtual void SetLockConstantBuffer(ShaderStage shaderStage, unsigned int slot, ConstantBuffer* buffer) = 0;
        virtual void ResetUnlockConstantBuffer(ShaderStage shaderStage, unsigned int slot, ConstantBuffer* buffer) = 0;
        virtual void ResetUnlockShaderResourceView(ShaderStage shaderStage, unsigned int slot) = 0;
        virtual void ResetUnlockSampler(ShaderStage shaderStage, unsigned int slot) = 0;
        virtual uint32_t DoNothing5() = 0;
        virtual uint64_t UnkFunc106() = 0;
        virtual InstanceParameterContainerData* GetInstanceParameterContainerData() const = 0;
        virtual bool DoNothing6() = 0;
        virtual uint64_t UnkFunc109() = 0;
        virtual bool DoNothing7() = 0;
        virtual void DoNothing8() = 0;
        virtual uint64_t UnkFunc111() = 0;
    };
}
